### ISSUE TITLE
Whatsapp link is  not working

### ISSUE THREAD

**Issue by sos10e** [pextech/Resume-React#1]
I was looking on your resume and tried to click on whatsapp icon
![image](https://user-images.githubusercontent.com/42154315/111520633-f6134400-8760-11eb-8b38-ecbd37019316.png)
and got this `message`

![image](https://user-images.githubusercontent.com/42154315/111519312-9f593a80-875f-11eb-88ba-b54978d39d3f.png)
Maybe you can change the link to 
```
https://api.whatsapp.com/send?phone=number&text=text
```

**Comment by pextech** [comment]
@sos10e this is because you are using a computer, this link usually works on mobile phone
